// <auto-generated />
using Application1.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Application1.Migrations
{
    [DbContext(typeof(Student_Course_DBContext))]
    partial class Student_Course_DBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Application1.Models.Course.Course", b =>
                {
                    b.Property<int>("CourseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CourseId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Duration")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.HasKey("CourseId");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            CourseId = 201,
                            Description = "A well designed react course",
                            Duration = "10hrs",
                            Name = "React Course",
                            Price = 0
                        },
                        new
                        {
                            CourseId = 202,
                            Description = "A well designed nodejs course",
                            Duration = "12hrs",
                            Name = "NodeJS Course",
                            Price = 0
                        },
                        new
                        {
                            CourseId = 203,
                            Description = "A good C# course",
                            Duration = "8hrs",
                            Name = "C# Course",
                            Price = 0
                        },
                        new
                        {
                            CourseId = 204,
                            Description = "A full .Net course",
                            Duration = "20hrs",
                            Name = ".Net Course",
                            Price = 0
                        },
                        new
                        {
                            CourseId = 205,
                            Description = "A well designed angular course",
                            Duration = "8hrs",
                            Name = "Angular Course",
                            Price = 0
                        });
                });

            modelBuilder.Entity("Application1.Models.Student.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.PrimitiveCollection<string>("CourseId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Standard")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Students");
                });
#pragma warning restore 612, 618
        }
    }
}
